import { supabaseHelpers } from './supabase';

/**
 * Defines the usage limits for different features based on subscription plans.
 */
export const USAGE_LIMITS = {
  // Total number of notes a user can store
  FREE_NOTES: 10,
  PRO_NOTES: Infinity,

  // Number of notes that can be generated by AI per month
  FREE_AI_NOTES_PER_MONTH: 5,
  PRO_AI_NOTES_PER_MONTH: Infinity,
} as const;

export interface UsageLimitResult {
  canCreate: boolean;
  currentCount: number;
  limit: number;
  plan: 'free' | 'pro';
}

/**
 * Checks the total notes usage limit for a user.
 * This determines if a user can manually create more notes.
 * @param userId The UUID of the user.
 * @returns An object detailing the user's current usage and limits.
 */
export async function checkNotesUsageLimit(userId: string): Promise<UsageLimitResult> {
  const userPlan = await supabaseHelpers.getUserWithPlan(userId);
  const currentCount = await supabaseHelpers.getNotesCount(userId);
  
  const limit = userPlan.subscription_plan === 'pro' ? USAGE_LIMITS.PRO_NOTES : USAGE_LIMITS.FREE_NOTES;
  const canCreate = currentCount < limit;
  
  return {
    canCreate,
    currentCount,
    limit,
    plan: userPlan.subscription_plan as 'free' | 'pro'
  };
}

/**
 * Validates if a user is allowed to manually create a new note based on their total note count.
 * @param userId The UUID of the user.
 * @returns An object indicating if the creation is valid, along with an optional error message.
 */
export async function validateNoteCreation(userId: string): Promise<{ 
  isValid: boolean; 
  error?: string; 
  message?: string;
  usageInfo?: UsageLimitResult;
}> {
  const usageInfo = await checkNotesUsageLimit(userId);
  
  if (!usageInfo.canCreate) {
    return {
      isValid: false,
      error: 'Note limit reached. Upgrade to Pro for unlimited notes.',
      message: `You have reached your limit of ${usageInfo.limit} notes. Current plan: ${usageInfo.plan === 'pro' ? 'Pro' : 'Free'}`,
      usageInfo
    };
  }
  
  return {
    isValid: true,
    usageInfo
  };
}

/**
 * Checks the AI-generated notes usage limit for a user for the current month.
 * @param userId The UUID of the user.
 * @returns An object detailing the user's current AI generation usage and limits for the month.
 */
export async function checkAIGenerationUsageLimit(userId: string): Promise<{ 
  canGenerate: boolean; 
  currentCount: number; 
  limit: number; 
}> {
  const userPlan = await supabaseHelpers.getUserWithPlan(userId);
  const currentCount = await supabaseHelpers.getAIGenerationUsage(userId, new Date());
  
  const limit = userPlan.subscription_plan === 'pro' 
    ? USAGE_LIMITS.PRO_AI_NOTES_PER_MONTH 
    : USAGE_LIMITS.FREE_AI_NOTES_PER_MONTH;

  const canGenerate = currentCount < limit;
  
  return {
    canGenerate,
    currentCount,
    limit,
  };
}