// src/app/api/documents/[documentId]/generate/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { 
  generateDocumentSummary, 
  generateQuizFromText, 
  generateFlashcardsFromText 
} from '@/lib/ai-service';

// Maximize execution time for Hobby Plan (60s)
export const maxDuration = 60; 

export async function POST(
  req: NextRequest,
  { params }: { params: { documentId: string } }
) {
  try {
    const user = await requireAuth(req);
    const { documentId } = params;
    
    // Get the specific task from query params (e.g., ?type=quiz)
    const { searchParams } = new URL(req.url);
    const type = searchParams.get('type'); // 'notes', 'quiz', 'flashcards'

    if (!['notes', 'quiz', 'flashcards'].includes(type || '')) {
      return NextResponse.json({ error: "Invalid or missing 'type' parameter" }, { status: 400 });
    }

    // 1. Fetch Document Text
    const doc = await prisma.documents.findUnique({
      where: { id: documentId, user_id: user.id },
      select: { id: true, extracted_text: true, file_name: true }
    });

    if (!doc || !doc.extracted_text) {
      return NextResponse.json({ error: "Document text not found" }, { status: 404 });
    }

    const textContext = doc.extracted_text;
    const baseTitle = doc.file_name.replace(/\.[^/.]+$/, "");

    // 2. Switch on Task Type
    let result;
    
    if (type === 'notes') {
      const summary = await generateDocumentSummary(textContext, baseTitle);
      result = await prisma.notes.create({
        data: {
          user_id: user.id,
          document_id: doc.id,
          title: `${baseTitle} - Study Notes`,
          content: summary,
          tags: ['ai-generated']
        }
      });
    } 
    
    else if (type === 'quiz') {
      const questionsData = await generateQuizFromText(textContext, 10);
      result = await prisma.quiz.create({
        data: {
          userId: user.id,
          document_id: doc.id,
          title: `${baseTitle} - Practice Quiz`,
          questions: {
            create: questionsData.map((q: any) => ({
              question_text: q.question_text,
              question_type: q.question_type,
              correct_answer: q.correct_answer,
              options: q.options || [],
              explanation: q.explanation || "Generated by AI"
            }))
          }
        }
      });
    } 
    
    else if (type === 'flashcards') {
      const cardsData = await generateFlashcardsFromText(textContext, 15);
      result = await prisma.flashcard_decks.create({
        data: {
          user_id: user.id,
          document_id: doc.id,
          title: `${baseTitle} - Key Terms`,
          flashcards: {
            create: cardsData.map((c: any) => ({
              front_content: c.front,
              back_content: c.back
            }))
          }
        }
      });
    }

    return NextResponse.json({ success: true, type, data: result });

  } catch (error: any) {
    console.error(`Generation Error (${params.documentId}):`, error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}